# Nombre del pipeline
name: Azure-Gradle-Pipeline

# Trigger del pipeline (por ejemplo, en cada cambio en la rama main)
trigger:
  branches:
    include:
      - main

# Pools de ejecución (puedes cambiarlo según tus necesidades)
pool:
  vmImage: 'ubuntu-latest'

# Pasos del pipeline
jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - task: UseGradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'

- job: SonarQube
  displayName: 'SonarQube Analysis'
  steps:
  - task: UseGradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'sonarqube'

# Puedes agregar más pasos según tus necesidades, como despliegue a servicios en la nube, publicación de artefactos, etc.
