# Nombre del pipeline. Cambiar "My CI Pipeline" a un nombre descriptivo.
name: My CI Pipeline

# El agente en el que se ejecutará el pipeline. Puedes especificar "ubuntu-latest" u otros disponibles.
trigger:
  branches:
    include:
      - master  # Configura aquí la rama que quieres que active el CI.

# Puedes especificar variables aquí si las necesitas en tus tareas.

# Etapas del pipeline.
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        displayName: Build Job
        pool:
          vmImage: 'ubuntu-latest'  # Configura el agente que quieres usar.

        steps:
          - script: echo 'Ejecutando tareas de construcción...'
            displayName: 'Construir'

# Puedes agregar más etapas y trabajos según tus necesidades.
