#spring.application.name=servicio-plazoleta
#server.port=8082
##eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/plazoleta
#spring.datasource.username=root
#spring.datasource.password=sandoval
##mostramos las sentencias sql en consola que se ejecutan
#spring.jpa.show-sql=true
##evitamos que las tablas y datos se eliminen.
#spring.jpa.hibernate.ddl-auto=update


server:
  port: 8082

spring:
  application:
    name: plazoleta-service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#sonar:
#  token: 32c1f56f1a380cbda7c41a2bbde8222c3345b4cc

#eureka:
#  #  client:
#  #    fetch-registry: false
#  #    register-with-eureka: false
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

appDescription: "Pragma usuario"

---
spring:
  profile: dev
  datasource:
    url: jdbc:mysql://plazoleta.ck02djlfmjed.us-east-1.rds.amazonaws.com:3306/plazoleta
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: sandoval
#    hikari:
#      pool-name: HikariPool-1
#      maximum-pool-size: 10
#      minimum-idle: 5
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      idle-timeout: 600000
#      validation-timeout: 5000

#appVersion: "1.0.0"

#//LOS ESPACIOS ENTRE ETIQUETAS SON MUY IMPORTANTES