

server:
  port: 8082

spring:
  application:
    name: plazoleta-service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



appDescription: "Pragma usuario"

---
spring:
  profile: prueba
  datasource:
    url: jdbc:mysql://plazoleta.ck02djlfmjed.us-east-1.rds.amazonaws.com:3306/plazoleta
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: sandoval

---
spring:
  profile: dev
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://plazoleta.ck02djlfmjed.us-east-1.rds.amazonaws.com:3306/plazoleta}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:sandoval}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}


















#    hikari:
#      pool-name: HikariPool-1
#      maximum-pool-size: 10
#      minimum-idle: 5
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      idle-timeout: 600000
#      validation-timeout: 5000

#appVersion: "1.0.0"

#//LOS ESPACIOS ENTRE ETIQUETAS SON MUY IMPORTANTES